### ISSUE TITLE
Failure with latest Hunspell

### ISSUE THREAD

**Issue by jeroen** [HughParsonage/TeXCheckR#12]
I have updated the bundled dictionaries in the `hunspell` package but now `TeXCheckR` fails it's checks. Could you help me debug what the issue is here?

```r
devtools::install_github("ropensci/hunspell")
```

**Comment by HughParsonage** [comment]
`TeXCheckR` used `XX` as a placeholder for an error in a particular unit test:

See https://travis-ci.org/HughParsonage/TeXCheckR/jobs/296321822 at line 2488.
```
Spellcheck failed: 'XX'
✖ 2: Box XX\@.
          ^^
```

whereas following the package update the spell check does not fail.

**Comment by jeroen** [comment]
Hmz so the word `XX` was added to the dictionary? Or is there something else going on?

**Comment by HughParsonage** [comment]
Yes, added to the dictionary; nothing else going on. 

As you might have seen, that build was only 20 hours ago, and it determined `XX` was a spelling error according to `hunspell`.

Frankly, my test requiring an error when `XX` is seen is not very good test since it's a valid roman numeral. I just included it because it did reliably fail. If `hunspell`'s dictionary is updated at the cost of this test, so be it. I would just change the test.

**Comment by jeroen** [comment]
OK is there any chance you can update that test to some word that will more reliably fail and submit to CRAN? I can't submit the hunspell update until this problem is resolved :(

**Comment by HughParsonage** [comment]
Yes, of course: sorry for delaying the release. I only recently updated `TeXCheckR`, however. CRAN might reject my package on the grounds of too frequent updates, but I'll try to explain the situation in my submission.

Do you anticipate any further updates before you lodge with CRAN?

**Comment by jeroen** [comment]
Ah well if they make a fuz I can temporary remove the word `xx` from the dictionary. Such a silly blocker. Don't expect further upgrades; I had already submitted but they rejected because it broke TeXCheckR.

**Comment by jeroen** [comment]
The new version of `hunspell` is on CRAN now. So you can submit `TeXCheckR` and then add a comment that this fixes the problem with the new hunspell pkg.

**Comment by HughParsonage** [comment]
On CRAN now.
