### ISSUE TITLE
Unescaped % sentinel in non-url fields

### ISSUE THREAD

**Issue by HughParsonage** [HughParsonage/TeXCheckR#44]
A problem in Lucy's report was a % in a title that caused an arcane error

```bibtex
@Article{BlakersLuStocks2017,
  author  = {Andrew Blakers and Bin Lu and Matthew Stocks},
  title   = {100% renewable electricity in Australia},
  journal = {Energy},
  date    = {2017-08-15},
}
```

It would be nice to detect this with a better error message. @carmelachivers1 if you'd like to have a go too?

**Comment by carmelachivers1** [comment]
@HughParsonage sure thing!
