### ISSUE TITLE
uncaught error condition

### ISSUE THREAD

**Issue by shabbychef** [HughParsonage/TeXCheckR#79]
I believe you should be checking for a null `sep` in this line, not `sep_candidate`: https://github.com/HughParsonage/TeXCheckR/blob/05c862ca92a60ab484552ad064dd87659abfc29d/R/bib_parser.R#L78
Otherwise, a null `sep` can be passed through, which leads to an error some lines later. Trivial to fix.

**Comment by HughParsonage** [comment]
Correct and thank you for the PR!
