### ISSUE TITLE
any_bib_duplicates() throws errors on finding triplicates

### ISSUE THREAD

**Issue by jamesha95** [HughParsonage/TeXCheckR#81]
The first check in 
```
stopifnot(nrow(DT_with_all_duplicates) %% 2L == 0L,
              nrow(DT_with_all_duplicates) > 1L)
``` 
will throw an error if any triplicates are present. This breaks checkGrattanReporter. 

Hopefully it can be fixed by dropping the check `nrow(DT_with_all_duplicates) %% 2L == 0L`. This may make the subsequent printing of duplicates pairs not quite right (pairs after the triplet will be misaligned): 
`print(DT_with_all_duplicates[c(2 * dup - 1, 2 * dup)], row.names = FALSE)`
But it's fine, we can live with that.

**Comment by HughParsonage** [comment]
Thanks. Applied hotfix.
